In [8]:
import numpy as np

In [9]:
a1=np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
c=np.array([[1,2],[3,4]],complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [11]:
a1=np.empty((3,4))
a2=np.zeros((3,4))
a3=np.ones((3,4))
a4=np.full((3,4),7)
a1,a2,a3,a4

(array([[1.50183978e-311, 2.47032823e-322, 0.00000000e+000,
         0.00000000e+000],
        [1.11260619e-306, 3.76231868e+174, 6.81758538e-091,
         1.02290495e+166],
        [9.98570585e-048, 1.38347875e-047, 3.99910963e+252,
         9.96668435e-047]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]))

In [12]:
a1=np.random.random((4))
a2=np.arange(5)
a3=np.arange(1,20,2)
a4=np.linspace(0,2,6) # create and elements 6 element the range between 0 to 2, with fixed steps.
a1,a2,a3,a4

(array([0.62071933, 0.72660861, 0.13162866, 0.55897482]),
 array([0, 1, 2, 3, 4]),
 array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([0. , 0.4, 0.8, 1.2, 1.6, 2. ]))

In [13]:
a1=np.eye(3)
a2=np.identity(3)
a2,a2

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [14]:
a1=np.array([1,2,3,4],np.int32)
a2=np.array([1.1,2.2,3.3,4.4])
print(a1.dtype)
print(a2.dtype)
print(a1.itemsize)
print(a2.itemsize)
print(a1.nbytes)
print(a2.nbytes)
print(a1.data)
print(a1.strides)
print(a2.data)
print(a2.strides)


int32
float64
4
8
16
32
(4,)
(8,)


In [15]:
a1=np.array([1,2,3,4])
a2=np.array([[1,2,3,4],[5,6,7,8]])
print(a1.ndim)
print(a2.ndim)
print(a1.shape)
print(a2.shape)
print(a1.size)
print(a2.size)



1
2
(4,)
(2, 4)
4
8


In [16]:
# Arithmatic Operations


a1=np.array([[10,2,3,4],[5,6,7,8]])
a2=np.array([[1,1,1,1],[2,2,2,2]])
a3=a1+a2
a4=a1*a2
a5=a1-a2
a6=a1/a2
a7=a1%a2
a8=a1**a2
print(a1,end='\n\n')
print(a2,end='\n\n')
print(a3,end='\n\n')
print(a4,end="\n\n")
print(a5,end="\n\n")
print(a6,end="\n\n")
print(a7,end="\n\n")
print(a8,end="\n\n")

[[10  2  3  4]
 [ 5  6  7  8]]

[[1 1 1 1]
 [2 2 2 2]]

[[11  3  4  5]
 [ 7  8  9 10]]

[[10  2  3  4]
 [10 12 14 16]]

[[9 1 2 3]
 [3 4 5 6]]

[[10.   2.   3.   4. ]
 [ 2.5  3.   3.5  4. ]]

[[0 0 0 0]
 [1 0 1 0]]

[[10  2  3  4]
 [25 36 49 64]]



In [17]:
a=np.array([[1,2,3],[4,5,6]])
print(a,end="\n\n")
print(a.sum())
print(a.min())
print(a.max())
print(a.max(axis=0)) # row
print(a.max(axis=1)) # column
print(a.sum(axis=0))
print(a.sum(axis=1))
print()
print(a.cumsum(axis=0))
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))

[[1 2 3]
 [4 5 6]]

21
1
6
[4 5 6]
[3 6]
[5 7 9]
[ 6 15]

[[1 2 3]
 [5 7 9]]
3.5
3.5
[[1. 1.]
 [1. 1.]]
1.707825127659933


In [18]:
#Linear alrebra operations
print(a1)
print(a2)
a3=a1*a2
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

a4 = A @ B
a5=A.dot(B)
a6=np.dot(A,B)
print(a3)
print(a4)
print(a5)
print(a6)

[[10  2  3  4]
 [ 5  6  7  8]]
[[1 1 1 1]
 [2 2 2 2]]
[[10  2  3  4]
 [10 12 14 16]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [19]:
a1=np.array([[1,2,3,4],[5,6,7,8]])
print("Original",a1)
a2=a1.transpose()
print(a2)
a3=np.transpose(a1)
print(a3)

Original [[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [20]:
# Sum of diagonal elements
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[1,2,3,4],[5,6,7,8]])
s=np.trace(a1)
s2=np.trace(a2)
print(a1)
print(s)
print(a2)
print(s2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15
[[1 2 3 4]
 [5 6 7 8]]
7


In [21]:
a=np.array([[1,2],[3,4]])
b=np.linalg.inv(a)
print(a)
print(b)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
# Linear simultaneous equation
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
x=np.linalg.solve(a,b)
print(a)
print(b)
print(x)

[[3 1]
 [1 2]]
[9 8]
[2. 3.]


In [23]:
# Bitwise Opeations
a1=np.array([[10,2,3,4],[5,6,7,8]])
a2=np.array([[1,1,1,1],[2,2,2,2]])
a3=np.bitwise_and(a1,a2)
a4=np.bitwise_or(a1,a2)
a5=np.bitwise_xor(a1,a2)
a6=np.invert(a1)
a7=np.left_shift(a1,3)
a8=np.right_shift(a1,2)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a6)
print(a7)
print(a8)

[[10  2  3  4]
 [ 5  6  7  8]]
[[1 1 1 1]
 [2 2 2 2]]
[[0 0 1 0]
 [0 2 2 0]]
[[11  3  3  5]
 [ 7  6  7 10]]
[[11  3  2  5]
 [ 7  4  5 10]]
[[-11  -3  -4  -5]
 [ -6  -7  -8  -9]]
[[80 16 24 32]
 [40 48 56 64]]
[[2 0 0 1]
 [1 1 1 2]]


In [31]:
# Copy
a=np.array([[3,5,7],[1,5,2]])
b=a
print(b is a)
print(a is b)
b[0][0]=100
print(a)
print(b)
v=a.view()
print(a is v)
print(v is a)
v[0][0]=56
print(a)
print(v)

d=np.copy(a)
print(a is d)
print(d is a)
d[0][0]=98
print(a)
print(d)

True
True
[[100   5   7]
 [  1   5   2]]
[[100   5   7]
 [  1   5   2]]
False
False
[[56  5  7]
 [ 1  5  2]]
[[56  5  7]
 [ 1  5  2]]
False
False
[[56  5  7]
 [ 1  5  2]]
[[98  5  7]
 [ 1  5  2]]


In [35]:
# Sorting
a=np.array([[3,7,6],[1,5,2]])
b=np.array([[3,7,6],[1,5,2]])
print(a)
a.sort()
print(a)
print(b)
b.sort(axis=0) # column wise default row wise.
print(b)

[[3 7 6]
 [1 5 2]]
[[3 6 7]
 [1 2 5]]
[[3 7 6]
 [1 5 2]]
[[1 5 2]
 [3 7 6]]


In [ ]:
# Compresion
a=np.array([[3,7,6],[1,5,2]])
print(a)
print(a>5)

b=np.array([[3,1,2],[1,7,2]])
print(b)
print(a>b)


[[3 7 6]
 [1 5 2]]
[[False  True  True]
 [False False False]]
[[3 1 2]
 [1 7 2]]
[[False  True  True]
 [False False False]]


In [42]:
# Compresion
a=np.array([[3,7,6],[1,5,2]])
b=np.array([[3,7,6],[1,5,2]])
c=np.array([[3,7],[6,1],[5,2]])
print(a==b)
print(np.array_equal(a,b))
# print(a==c) gives error
print(np.array_equal(a,c))

[[ True  True  True]
 [ True  True  True]]
True
False


In [51]:
# indexing and slicing
a=np.array([3,7,6,1,5,2])
print(a[0])
b=np.array([[1,5,2],[3,7,6]])
print(b[0][1])
print(a[2:5])
print(a[-4])
print(a[:-4])
c=np.array([[3,7,6,9,8],[1,5,9,2,4],[0,0,3,1,5]])
print(c)
print(c[1:3,2:4])

3
5
[6 1 5]
6
[3 7]
[[3 7 6 9 8]
 [1 5 9 2 4]
 [0 0 3 1 5]]
[[9 2]
 [3 1]]


In [57]:
a=np.array([[3,7,6,9],[1,5,2,4],[0,3,1,5]]) #3x4
print(a)
print(a.shape)
b=a.reshape(2,6)
print(b)
c=a.reshape(4,-1) # -1 means auto calcucalte like 3x4=12 so first 4 and second is 12/4= 3 4x3 matrix
print(c)

[[3 7 6 9]
 [1 5 2 4]
 [0 3 1 5]]
(3, 4)
[[3 7 6 9 1 5]
 [2 4 0 3 1 5]]
[[3 7 6]
 [9 1 5]
 [2 4 0]
 [3 1 5]]


In [59]:
# Convert to flat aarray
a=np.array([[3,7,6,9],[1,5,2,4],[0,3,1,5]]) #3x4
b=a.ravel()
print(b)

[3 7 6 9 1 5 2 4 0 3 1 5]


In [61]:
# Append
a=np.array([[3,7,6,9],[1,5,2,4]])
b=np.array([[0,3,1,5],[1,1,1,1]])
print(a)
print(b)
c=np.append(a,b,axis=0)
d=np.append(a,b,axis=1)
print()
print(c)
print()
print(d)


[[3 7 6 9]
 [1 5 2 4]]
[[0 3 1 5]
 [1 1 1 1]]

[[3 7 6 9]
 [1 5 2 4]
 [0 3 1 5]
 [1 1 1 1]]

[[3 7 6 9 0 3 1 5]
 [1 5 2 4 1 1 1 1]]
